
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed14;

	private global::Gtk.Label label6;

	private global::Gtk.RadioButton radiobutton5;

	private global::Gtk.RadioButton radiobutton6;

	private global::Gtk.CheckButton checkbutton5;

	private global::Gtk.CheckButton checkbutton6;

	private global::Gtk.Image image4;

	private global::Gtk.SpinButton spinbutton3;

	private global::Gtk.ScrolledWindow GtkScrolledWindow;

	private global::Gtk.TextView textview2;

	private global::Gtk.ScrolledWindow GtkScrolledWindow1;

	private global::Gtk.TreeView treeview2;

	private global::Gtk.ComboBox combobox20;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed14 = new global::Gtk.Fixed();
		this.fixed14.Name = "fixed14";
		this.fixed14.HasWindow = false;
		// Container child fixed14.Gtk.Fixed+FixedChild
		this.label6 = new global::Gtk.Label();
		this.label6.Name = "label6";
		this.label6.LabelProp = global::Mono.Unix.Catalog.GetString("label6");
		this.fixed14.Add(this.label6);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed14[this.label6]));
		w1.X = 51;
		w1.Y = 48;
		// Container child fixed14.Gtk.Fixed+FixedChild
		this.radiobutton5 = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("radiobutton5"));
		this.radiobutton5.CanFocus = true;
		this.radiobutton5.Name = "radiobutton5";
		this.radiobutton5.DrawIndicator = true;
		this.radiobutton5.UseUnderline = true;
		this.radiobutton5.Group = new global::GLib.SList(global::System.IntPtr.Zero);
		this.fixed14.Add(this.radiobutton5);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed14[this.radiobutton5]));
		w2.X = 351;
		w2.Y = 40;
		// Container child fixed14.Gtk.Fixed+FixedChild
		this.radiobutton6 = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("radiobutton6"));
		this.radiobutton6.CanFocus = true;
		this.radiobutton6.Name = "radiobutton6";
		this.radiobutton6.DrawIndicator = true;
		this.radiobutton6.UseUnderline = true;
		this.radiobutton6.Group = this.radiobutton5.Group;
		this.fixed14.Add(this.radiobutton6);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed14[this.radiobutton6]));
		w3.X = 351;
		w3.Y = 96;
		// Container child fixed14.Gtk.Fixed+FixedChild
		this.checkbutton5 = new global::Gtk.CheckButton();
		this.checkbutton5.CanFocus = true;
		this.checkbutton5.Name = "checkbutton5";
		this.checkbutton5.Label = global::Mono.Unix.Catalog.GetString("checkbutton5");
		this.checkbutton5.DrawIndicator = true;
		this.checkbutton5.UseUnderline = true;
		this.fixed14.Add(this.checkbutton5);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed14[this.checkbutton5]));
		w4.X = 161;
		w4.Y = 45;
		// Container child fixed14.Gtk.Fixed+FixedChild
		this.checkbutton6 = new global::Gtk.CheckButton();
		this.checkbutton6.CanFocus = true;
		this.checkbutton6.Name = "checkbutton6";
		this.checkbutton6.Label = global::Mono.Unix.Catalog.GetString("checkbutton6");
		this.checkbutton6.DrawIndicator = true;
		this.checkbutton6.UseUnderline = true;
		this.fixed14.Add(this.checkbutton6);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed14[this.checkbutton6]));
		w5.X = 160;
		w5.Y = 101;
		// Container child fixed14.Gtk.Fixed+FixedChild
		this.image4 = new global::Gtk.Image();
		this.image4.Name = "image4";
		this.fixed14.Add(this.image4);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed14[this.image4]));
		w6.X = 52;
		w6.Y = 190;
		// Container child fixed14.Gtk.Fixed+FixedChild
		this.spinbutton3 = new global::Gtk.SpinButton(0D, 100D, 1D);
		this.spinbutton3.CanFocus = true;
		this.spinbutton3.Name = "spinbutton3";
		this.spinbutton3.Adjustment.PageIncrement = 10D;
		this.spinbutton3.ClimbRate = 1D;
		this.spinbutton3.Numeric = true;
		this.fixed14.Add(this.spinbutton3);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed14[this.spinbutton3]));
		w7.X = 367;
		w7.Y = 165;
		// Container child fixed14.Gtk.Fixed+FixedChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.textview2 = new global::Gtk.TextView();
		this.textview2.WidthRequest = 135;
		this.textview2.HeightRequest = 106;
		this.textview2.CanFocus = true;
		this.textview2.Name = "textview2";
		this.GtkScrolledWindow.Add(this.textview2);
		this.fixed14.Add(this.GtkScrolledWindow);
		global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed14[this.GtkScrolledWindow]));
		w9.X = 176;
		w9.Y = 167;
		// Container child fixed14.Gtk.Fixed+FixedChild
		this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
		this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
		this.treeview2 = new global::Gtk.TreeView();
		this.treeview2.WidthRequest = 227;
		this.treeview2.HeightRequest = 101;
		this.treeview2.CanFocus = true;
		this.treeview2.Name = "treeview2";
		this.GtkScrolledWindow1.Add(this.treeview2);
		this.fixed14.Add(this.GtkScrolledWindow1);
		global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed14[this.GtkScrolledWindow1]));
		w11.X = 29;
		w11.Y = 321;
		// Container child fixed14.Gtk.Fixed+FixedChild
		this.combobox20 = global::Gtk.ComboBox.NewText();
		this.combobox20.WidthRequest = 218;
		this.combobox20.Name = "combobox20";
		this.fixed14.Add(this.combobox20);
		global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed14[this.combobox20]));
		w12.X = 383;
		w12.Y = 320;
		this.Add(this.fixed14);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 630;
		this.DefaultHeight = 456;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
	}
}
