
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed13;

	private global::wegeTest1.ComboWidget combowidget1;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed13 = new global::Gtk.Fixed();
		this.fixed13.Name = "fixed13";
		this.fixed13.HasWindow = false;
		// Container child fixed13.Gtk.Fixed+FixedChild
		this.combowidget1 = new global::wegeTest1.ComboWidget();
		this.combowidget1.WidthRequest = 150;
		this.combowidget1.Events = ((global::Gdk.EventMask)(256));
		this.combowidget1.Name = "combowidget1";
		this.fixed13.Add(this.combowidget1);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed13[this.combowidget1]));
		w1.X = 109;
		w1.Y = 97;
		this.Add(this.fixed13);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 300;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
	}
}
