
// This file has been generated by the GUI designer. Do not modify.
namespace wegeTest1
{
	public partial class ComboWidget
	{
		private global::Gtk.ComboBox combobox15;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget wegeTest1.ComboWidget
			global::Stetic.BinContainer.Attach(this);
			this.Name = "wegeTest1.ComboWidget";
			// Container child wegeTest1.ComboWidget.Gtk.Container+ContainerChild
			this.combobox15 = global::Gtk.ComboBox.NewText();
			this.combobox15.Name = "combobox15";
			this.Add(this.combobox15);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
